//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Export
    {
        public long Id { get; set; }
        public string CusName { get; set; }
        public string Hub { get; set; }
        public string Center { get; set; }
        public string Import_Warehouse { get; set; }
        public string Address { get; set; }
        public string Export_Warehouse { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public string Boss { get; set; }
        public int Quantity { get; set; }
        public int Amount { get; set; }
        public int Total { get; set; }
        public int Discount { get; set; }
        public int Status { get; set; }
        public Nullable<long> WarrantiId { get; set; }
    }
}
