//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediamart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCrack
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public string Name { get; set; }
        public string Serial { get; set; }
        public string Code { get; set; }
        public string Model { get; set; }
        public int Status { get; set; }
        public string Note { get; set; }
        public string CodeWarranti { get; set; }
        public string SNNo { get; set; }
        public string Station { get; set; }
    }
}
